/**
 * Reads pre-computed PnL data from CSV files and returns it in the shapes
 * expected by the frontend PnlTable component.
 *
 * CSV files are generated by: npm run export-pnl
 * Location: data/pnl-export/monthly_pnl.csv, quarterly_pnl.csv, yearly_summary.csv
 *
 * Lazy-loads and caches in memory. Reloads automatically if files change on disk.
 */

import * as fs from "fs";
import * as path from "path";

// ---------------------------------------------------------------------------
// Types matching frontend expectations
// ---------------------------------------------------------------------------

interface MonthlyPnl {
  [year: string]: {
    months: {
      [monthName: string]: {
        percent: string;
        cash: string;
        capitalInOut: string;
      };
    };
    totalPercent: number;
    totalCash: number;
    totalCapitalInOut: number;
  };
}

interface QuarterlyPnl {
  [year: string]: {
    percent: { q1: string; q2: string; q3: string; q4: string; total: string };
    cash: { q1: string; q2: string; q3: string; q4: string; total: string };
    yearCash: string;
  };
}

// ---------------------------------------------------------------------------
// Internal row types
// ---------------------------------------------------------------------------

interface MonthlyRow {
  identifier: string;
  scheme: string;
  year: string;
  month: number;
  percent: string;
  cash: string;
  capitalInOut: string;
}

interface QuarterlyRow {
  identifier: string;
  scheme: string;
  year: string;
  quarter: number;
  percent: string;
  cash: string;
}

interface YearlyRow {
  identifier: string;
  scheme: string;
  year: string;
  totalPercent: string;
  totalCash: string;
  totalCapitalInOut: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const CSV_DIR = path.join(process.cwd(), "data", "pnl-export");
const MONTHLY_CSV = path.join(CSV_DIR, "monthly_pnl.csv");
const QUARTERLY_CSV = path.join(CSV_DIR, "quarterly_pnl.csv");
const YEARLY_CSV = path.join(CSV_DIR, "yearly_summary.csv");

// ---------------------------------------------------------------------------
// Cache
// ---------------------------------------------------------------------------

type IndexKey = string; // "identifier|scheme"

let monthlyIndex: Map<IndexKey, MonthlyRow[]> | null = null;
let quarterlyIndex: Map<IndexKey, QuarterlyRow[]> | null = null;
let yearlyIndex: Map<IndexKey, Map<string, YearlyRow>> | null = null;

let cachedMtimes: { monthly: number; quarterly: number; yearly: number } = {
  monthly: 0,
  quarterly: 0,
  yearly: 0,
};

function makeKey(identifier: string, scheme: string): IndexKey {
  return `${identifier}|${scheme}`;
}

// ---------------------------------------------------------------------------
// CSV parsing
// ---------------------------------------------------------------------------

function parseCsvLines(filePath: string): string[][] {
  const content = fs.readFileSync(filePath, "utf-8");
  const lines = content.trim().split("\n");
  // Skip header, parse data rows
  return lines.slice(1).map((line) => line.split(","));
}

function getMtime(filePath: string): number {
  try {
    return fs.statSync(filePath).mtimeMs;
  } catch {
    return 0;
  }
}

function needsReload(): boolean {
  const m = getMtime(MONTHLY_CSV);
  const q = getMtime(QUARTERLY_CSV);
  const y = getMtime(YEARLY_CSV);
  return (
    m !== cachedMtimes.monthly ||
    q !== cachedMtimes.quarterly ||
    y !== cachedMtimes.yearly
  );
}

function loadAll(): boolean {
  try {
    if (!fs.existsSync(MONTHLY_CSV) || !fs.existsSync(QUARTERLY_CSV) || !fs.existsSync(YEARLY_CSV)) {
      console.warn("[precomputed-pnl] CSV files not found in", CSV_DIR);
      return false;
    }

    // Parse monthly
    const mRows = parseCsvLines(MONTHLY_CSV);
    const mIndex = new Map<IndexKey, MonthlyRow[]>();
    for (const cols of mRows) {
      if (cols.length < 7) continue;
      const row: MonthlyRow = {
        identifier: cols[0].trim(),
        scheme: cols[1].trim(),
        year: cols[2].trim(),
        month: parseInt(cols[3].trim(), 10),
        percent: cols[4].trim(),
        cash: cols[5].trim(),
        capitalInOut: cols[6].trim(),
      };
      const key = makeKey(row.identifier, row.scheme);
      if (!mIndex.has(key)) mIndex.set(key, []);
      mIndex.get(key)!.push(row);
    }

    // Parse quarterly
    const qRows = parseCsvLines(QUARTERLY_CSV);
    const qIndex = new Map<IndexKey, QuarterlyRow[]>();
    for (const cols of qRows) {
      if (cols.length < 6) continue;
      const row: QuarterlyRow = {
        identifier: cols[0].trim(),
        scheme: cols[1].trim(),
        year: cols[2].trim(),
        quarter: parseInt(cols[3].trim(), 10),
        percent: cols[4].trim(),
        cash: cols[5].trim(),
      };
      const key = makeKey(row.identifier, row.scheme);
      if (!qIndex.has(key)) qIndex.set(key, []);
      qIndex.get(key)!.push(row);
    }

    // Parse yearly
    const yRows = parseCsvLines(YEARLY_CSV);
    const yIndex = new Map<IndexKey, Map<string, YearlyRow>>();
    for (const cols of yRows) {
      if (cols.length < 6) continue;
      const row: YearlyRow = {
        identifier: cols[0].trim(),
        scheme: cols[1].trim(),
        year: cols[2].trim(),
        totalPercent: cols[3].trim(),
        totalCash: cols[4].trim(),
        totalCapitalInOut: cols[5].trim(),
      };
      const key = makeKey(row.identifier, row.scheme);
      if (!yIndex.has(key)) yIndex.set(key, new Map());
      yIndex.get(key)!.set(row.year, row);
    }

    monthlyIndex = mIndex;
    quarterlyIndex = qIndex;
    yearlyIndex = yIndex;
    cachedMtimes = {
      monthly: getMtime(MONTHLY_CSV),
      quarterly: getMtime(QUARTERLY_CSV),
      yearly: getMtime(YEARLY_CSV),
    };

    console.log(
      `[precomputed-pnl] Loaded ${mIndex.size} monthly keys, ${qIndex.size} quarterly keys, ${yIndex.size} yearly keys`
    );
    return true;
  } catch (err: any) {
    console.warn("[precomputed-pnl] Failed to load CSVs:", err.message);
    return false;
  }
}

function ensureLoaded(): boolean {
  if (!monthlyIndex || !quarterlyIndex || !yearlyIndex || needsReload()) {
    return loadAll();
  }
  return true;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function getPrecomputedMonthlyPnl(
  icode: string,
  scheme: string
): MonthlyPnl | null {
  if (!ensureLoaded()) return null;

  const key = makeKey(icode, scheme);
  const rows = monthlyIndex!.get(key);
  if (!rows || rows.length === 0) return null;

  const yearlyMap = yearlyIndex!.get(key);
  const result: MonthlyPnl = {};

  // Group by year
  const byYear = new Map<string, MonthlyRow[]>();
  for (const row of rows) {
    if (!byYear.has(row.year)) byYear.set(row.year, []);
    byYear.get(row.year)!.push(row);
  }

  for (const [year, yearRows] of byYear) {
    const months: MonthlyPnl[string]["months"] = {};
    for (const row of yearRows) {
      const monthName = MONTH_NAMES[row.month - 1];
      if (!monthName) continue;
      months[monthName] = {
        percent: row.percent || "-",
        cash: row.cash || "-",
        capitalInOut: row.capitalInOut || "-",
      };
    }

    // Yearly totals from yearly_summary.csv
    const ySummary = yearlyMap?.get(year);
    const totalPercent = ySummary?.totalPercent
      ? parseFloat(ySummary.totalPercent)
      : 0;
    const totalCash = ySummary?.totalCash
      ? parseFloat(ySummary.totalCash)
      : 0;
    const totalCapitalInOut = ySummary?.totalCapitalInOut
      ? parseFloat(ySummary.totalCapitalInOut)
      : 0;

    result[year] = {
      months,
      totalPercent,
      totalCash,
      totalCapitalInOut,
    };
  }

  return result;
}

export function getPrecomputedQuarterlyPnl(
  icode: string,
  scheme: string
): QuarterlyPnl | null {
  if (!ensureLoaded()) return null;

  const key = makeKey(icode, scheme);
  const rows = quarterlyIndex!.get(key);
  if (!rows || rows.length === 0) return null;

  const result: QuarterlyPnl = {};

  // Group by year
  const byYear = new Map<string, QuarterlyRow[]>();
  for (const row of rows) {
    if (!byYear.has(row.year)) byYear.set(row.year, []);
    byYear.get(row.year)!.push(row);
  }

  for (const [year, yearRows] of byYear) {
    const percent: Record<string, string> = { q1: "-", q2: "-", q3: "-", q4: "-", total: "-" };
    const cash: Record<string, string> = { q1: "0.00", q2: "0.00", q3: "0.00", q4: "0.00", total: "0.00" };

    let compoundedReturn = 1;
    let hasAnyPercent = false;
    let cashTotal = 0;

    for (const row of yearRows) {
      const qKey = `q${row.quarter}`;
      percent[qKey] = row.percent || "-";
      cash[qKey] = row.cash || "0.00";

      if (row.percent && row.percent !== "-" && row.percent !== "") {
        const pVal = parseFloat(row.percent);
        if (!isNaN(pVal)) {
          compoundedReturn *= 1 + pVal / 100;
          hasAnyPercent = true;
        }
      }

      const cVal = parseFloat(row.cash);
      if (!isNaN(cVal)) cashTotal += cVal;
    }

    percent.total = hasAnyPercent
      ? ((compoundedReturn - 1) * 100).toFixed(2)
      : "-";
    cash.total = cashTotal.toFixed(2);

    result[year] = {
      percent: percent as QuarterlyPnl[string]["percent"],
      cash: cash as QuarterlyPnl[string]["cash"],
      yearCash: cashTotal.toFixed(2),
    };
  }

  return result;
}
