"use client";

import { useEffect, useRef, useState } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import JSZip from "jszip";
import { AdminHeader } from "@/components/admin/AdminHeader";
import { Button } from "@/components/ui/button";
import { Download, FileSpreadsheet, Loader2, CheckCircle2, AlertCircle } from "lucide-react";

type State = "idle" | "loading" | "done" | "error";
type Stage = "dashboard" | "holdings";

// Clients per request. Each batch is generated by one HTTP request — keeping
// batches small means every request finishes well within any reverse-proxy
// timeout, instead of one long request for the whole client list.
const BATCH_SIZE = 10;

function chunk<T>(items: T[], size: number): T[][] {
  const batches: T[][] = [];
  for (let i = 0; i < items.length; i += size) batches.push(items.slice(i, i + size));
  return batches;
}

export default function DownloadAllExcelsPage() {
  const { data: session, status } = useSession();
  const router = useRouter();

  const [state, setState]       = useState<State>("idle");
  const [stage, setStage]       = useState<Stage>("dashboard");
  const [progress, setProgress] = useState(0);      // 0-100 animated estimate per batch
  const [elapsed, setElapsed]   = useState(0);
  const [errorMsg, setErrorMsg] = useState("");
  const [batchInfo, setBatchInfo] = useState({ index: 0, total: 0 });
  const timerRef    = useRef<ReturnType<typeof setInterval> | null>(null);
  const progressRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const startRef    = useRef(0);

  useEffect(() => {
    if (status === "unauthenticated") router.push("/");
    if (status === "authenticated" && session?.user?.accessType !== "admin") router.push("/dashboard");
  }, [status, session, router]);

  function startTimers() {
    startRef.current = Date.now();
    setElapsed(0);
    setProgress(0);

    // Elapsed counter
    timerRef.current = setInterval(() => {
      setElapsed(Math.floor((Date.now() - startRef.current) / 1000));
    }, 1000);

    // Animated progress bar — slow fill that never quite reaches 100%
    // It accelerates at first then slows down, so it feels responsive
    // without lying about completion.
    progressRef.current = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 90) return prev + 0.05;   // crawl near the end
        if (prev >= 70) return prev + 0.3;
        if (prev >= 40) return prev + 0.8;
        return prev + 1.5;
      });
    }, 300);
  }

  function stopTimers() {
    if (timerRef.current)    clearInterval(timerRef.current);
    if (progressRef.current) clearInterval(progressRef.current);
  }

  // Trigger a browser download for a blob.
  function saveBlob(blob: Blob, filename: string) {
    const objectUrl = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = objectUrl;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(objectUrl);
  }

  // Fetch one stage in small batches (so no single request runs long enough to
  // hit a reverse-proxy timeout), then merge every batch's zip into a single
  // zip client-side so the user still gets one file per stage.
  async function buildMergedZipForStage(stageEndpoint: string, batches: string[][]): Promise<Blob> {
    const merged = new JSZip();
    const errorChunks: string[] = [];
    const total = batches.length;

    for (let i = 0; i < total; i++) {
      setBatchInfo({ index: i + 1, total });
      startTimers();

      const icodes = batches[i].join(",");
      const res = await fetch(`${stageEndpoint}?icodes=${encodeURIComponent(icodes)}`);
      if (!res.ok) {
        const json = await res.json().catch(() => ({}));
        throw new Error(json.error ?? `Server returned ${res.status}`);
      }
      const batchZip = await JSZip.loadAsync(await res.arrayBuffer());

      for (const entry of Object.values(batchZip.files)) {
        if (entry.dir) continue;
        if (entry.name === "_errors.txt") {
          errorChunks.push(`--- batch ${i + 1}/${total} ---\n${await entry.async("text")}`);
          continue;
        }
        merged.file(entry.name, await entry.async("blob"));
      }

      setProgress(100);
      stopTimers();
    }

    if (errorChunks.length > 0) merged.file("_errors.txt", errorChunks.join("\n\n"));
    return merged.generateAsync({ type: "blob" });
  }

  async function handleDownload() {
    setState("loading");
    setErrorMsg("");
    const date = new Date().toISOString().slice(0, 10);

    // Plan batches from the current client list (fast, read-only lookup).
    let batches: string[][];
    try {
      const res = await fetch("/api/admin/download-all-excels/clients");
      if (!res.ok) throw new Error(`Server returned ${res.status}`);
      const { icodes } = await res.json();
      batches = chunk(icodes as string[], BATCH_SIZE);
    } catch (e) {
      setErrorMsg(`Failed to plan batches: ${e instanceof Error ? e.message : String(e)}`);
      setState("error");
      return;
    }

    // ── Stage 1: dashboard ────────────────────────────────────────────────
    setStage("dashboard");
    try {
      const blob = await buildMergedZipForStage("/api/admin/download-all-excels/dashboard", batches);
      saveBlob(blob, `qode_dashboard_excels_${date}.zip`);
    } catch (e) {
      stopTimers();
      setErrorMsg(`Dashboard: ${e instanceof Error ? e.message : String(e)}`);
      setState("error");
      return;
    }

    // ── Stage 2: holdings ─────────────────────────────────────────────────
    setStage("holdings");
    try {
      const blob = await buildMergedZipForStage("/api/admin/download-all-excels/holdings", batches);
      saveBlob(blob, `qode_holdings_excels_${date}.zip`);
      setState("done");
    } catch (e) {
      setErrorMsg(`Holdings: ${e instanceof Error ? e.message : String(e)}`);
      setState("error");
    } finally {
      stopTimers();
    }
  }

  if (status === "loading" || status === "unauthenticated") return null;

  const isLoading = state === "loading";

  return (
    <div className="min-h-screen bg-primary-bg">
      <AdminHeader />

      <div className="max-w-xl mx-auto px-4 py-16 space-y-8">

        {/* Header */}
        <div className="text-center space-y-2">
          <div className="inline-flex items-center justify-center w-14 h-14 rounded-full bg-logo-green/10 mb-2">
            <FileSpreadsheet className="h-7 w-7 text-logo-green" />
          </div>
          <h1 className="text-2xl font-bold text-card-text font-heading">
            Download All Client Excels
          </h1>
          <p className="text-sm text-card-text-secondary">
            Generates two zips (fetched in small client batches behind the scenes)
          </p>
        </div>

        {/* Card */}
        <div className="bg-white/60 border border-card-text-secondary/20 rounded-2xl p-8 space-y-6">

          {/* Progress bar — visible only while loading */}
          {isLoading && (
            <div className="space-y-2">
              <div className="flex justify-between text-xs text-card-text-secondary">
                <span>
                  Step {stage === "dashboard" ? "1/2 — Dashboard" : "2/2 — Holdings"} Excels
                  {batchInfo.total > 1 ? ` (batch ${batchInfo.index}/${batchInfo.total})` : ""}…
                </span>
                <span>{Math.min(Math.floor(progress), 99)}%</span>
              </div>
              <div className="h-2 w-full bg-card-text-secondary/15 rounded-full overflow-hidden">
                <div
                  className="h-full bg-logo-green rounded-full transition-all duration-300"
                  style={{ width: `${Math.min(progress, 99)}%` }}
                />
              </div>
              <p className="text-xs text-card-text-secondary text-right">{elapsed}s elapsed</p>
            </div>
          )}

          {/* Done */}
          {state === "done" && (
            <div className="flex items-center gap-3 text-sm text-logo-green bg-green-50 border border-green-200 rounded-xl px-4 py-3">
              <CheckCircle2 className="h-4 w-4 shrink-0" />
              Both zips downloaded (dashboard + holdings). Check your downloads folder.
            </div>
          )}

          {/* Error */}
          {state === "error" && (
            <div className="flex items-start gap-3 text-sm text-red-700 bg-red-50 border border-red-200 rounded-xl px-4 py-3">
              <AlertCircle className="h-4 w-4 shrink-0 mt-0.5" />
              <span><strong>Failed:</strong> {errorMsg}</span>
            </div>
          )}

          {/* Button */}
          <Button
            onClick={handleDownload}
            disabled={isLoading}
            className="w-full bg-logo-green text-button-text hover:bg-logo-green/90 h-11 text-sm font-medium gap-2 disabled:opacity-60"
          >
            {isLoading ? (
              <><Loader2 className="h-4 w-4 animate-spin" /> Generating…</>
            ) : (
              <><Download className="h-4 w-4" /> {state === "done" ? "Download Again" : "Download All Excels"}</>
            )}
          </Button>

          {/* Note */}
          <p className="text-xs text-card-text-secondary text-center">
            Admin only · Files include all strategies per client · Benchmark columns will be blank
          </p>
        </div>
      </div>
    </div>
  );
}
