zerodha_total_portfolio: "Zerodha Total Portfolio"
equity_stock_holdings: "Equity Stock Holdings"
mutual_funds: "Mutual Funds"
liquidcase_stock_holdings: "Liquidcase Stock Holdings"
bond_stock_holdings: "Bond Stock Holdings"
liquidbees: "Liquidbees"
equity_other_debits_credits: "Equity Other Debits and Credits"
equity_holdings_tax: "Equity Holdings Tax"
miscellaneous_pnl: "Miscellaneous P&L"
total_portfolio_value: "Total Portfolio Value"
